# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.v1.internal.agent_backend import messages_pb2 as proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2


class ConversationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConversationMessages = channel.unary_unary(
                '/v1.internal.agent_backend.ConversationService/GetConversationMessages',
                request_serializer=proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesRequest.SerializeToString,
                response_deserializer=proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesResponse.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConversationMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConversationMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationMessages,
                    request_deserializer=proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesRequest.FromString,
                    response_serializer=proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.internal.agent_backend.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.internal.agent_backend.ConversationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConversationMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.internal.agent_backend.ConversationService/GetConversationMessages',
            proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesRequest.SerializeToString,
            proto_dot_v1_dot_internal_dot_agent__backend_dot_messages__pb2.GetConversationMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
