# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/v1/internal/agent_backend/messages.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/v1/internal/agent_backend/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.v1 import conversations_pb2 as proto_dot_v1_dot_conversations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.proto/v1/internal/agent_backend/messages.proto\x12\x19v1.internal.agent_backend\x1a\x1cproto/v1/conversations.proto\"I\n\x1eGetConversationMessagesRequest\x12\'\n\x0f\x63onversation_id\x18\x01 \x01(\tR\x0e\x63onversationId\"\x8f\x01\n\x13\x43onversationMessage\x12\x34\n\x0cuser_message\x18\x01 \x01(\x0b\x32\x0f.v1.UserMessageH\x00R\x0buserMessage\x12\x37\n\ragent_message\x18\x02 \x01(\x0b\x32\x10.v1.AgentMessageH\x00R\x0c\x61gentMessageB\t\n\x07message\"m\n\x1fGetConversationMessagesResponse\x12J\n\x08messages\x18\x01 \x03(\x0b\x32..v1.internal.agent_backend.ConversationMessageR\x08messages2\xa8\x01\n\x13\x43onversationService\x12\x90\x01\n\x17GetConversationMessages\x12\x39.v1.internal.agent_backend.GetConversationMessagesRequest\x1a:.v1.internal.agent_backend.GetConversationMessagesResponseB5Z3vynfo.com/vynfo/gen/proto/v1/internal/agent_backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.internal.agent_backend.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3vynfo.com/vynfo/gen/proto/v1/internal/agent_backend'
  _globals['_GETCONVERSATIONMESSAGESREQUEST']._serialized_start=107
  _globals['_GETCONVERSATIONMESSAGESREQUEST']._serialized_end=180
  _globals['_CONVERSATIONMESSAGE']._serialized_start=183
  _globals['_CONVERSATIONMESSAGE']._serialized_end=326
  _globals['_GETCONVERSATIONMESSAGESRESPONSE']._serialized_start=328
  _globals['_GETCONVERSATIONMESSAGESRESPONSE']._serialized_end=437
  _globals['_CONVERSATIONSERVICE']._serialized_start=440
  _globals['_CONVERSATIONSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
