"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from proto.v1.inter.agent_runtime import chat_pb2 as _chat_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(
    _abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta
): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ChatServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ChatServiceAsyncStub: ...
    StreamChat: _grpc.UnaryStreamMultiCallable[
        _chat_pb2.StreamChatRequest, _chat_pb2.StreamChatResponse
    ]

@_typing.type_check_only
class ChatServiceAsyncStub(ChatServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamChat: _aio.UnaryStreamMultiCallable[
        _chat_pb2.StreamChatRequest, _chat_pb2.StreamChatResponse
    ]  # type: ignore[assignment]

class ChatServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def StreamChat(
        self,
        request: _chat_pb2.StreamChatRequest,
        context: _ServicerContext,
    ) -> _typing.Union[
        _abc.Iterator[_chat_pb2.StreamChatResponse],
        _abc.AsyncIterator[_chat_pb2.StreamChatResponse],
    ]: ...

def add_ChatServiceServicer_to_server(
    servicer: ChatServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]
) -> None: ...
