# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/v1/conversations.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 0, "", "proto/v1/conversations.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cproto/v1/conversations.proto\x12\x02v1"\'\n\x0bUserMessage\x12\x18\n\x07\x63ontent\x18\x01 \x01(\tR\x07\x63ontent"(\n\x0c\x41gentMessage\x12\x18\n\x07\x63ontent\x18\x01 \x01(\tR\x07\x63ontentB\x1eZ\x1cvynfo.com/vynfo/gen/proto/v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "proto.v1.conversations_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\034vynfo.com/vynfo/gen/proto/v1"
    _globals["_USERMESSAGE"]._serialized_start = 36
    _globals["_USERMESSAGE"]._serialized_end = 75
    _globals["_AGENTMESSAGE"]._serialized_start = 77
    _globals["_AGENTMESSAGE"]._serialized_end = 117
# @@protoc_insertion_point(module_scope)
