# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.v1.inter.agent_backend import backend_pb2 as proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2


class AgentBackendServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticateUserAndPrompt = channel.unary_unary(
                '/v1.inter.agent_backend.AgentBackendService/AuthenticateUserAndPrompt',
                request_serializer=proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptRequest.SerializeToString,
                response_deserializer=proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptResponse.FromString,
                _registered_method=True)


class AgentBackendServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AuthenticateUserAndPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentBackendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticateUserAndPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateUserAndPrompt,
                    request_deserializer=proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptRequest.FromString,
                    response_serializer=proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.inter.agent_backend.AgentBackendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.inter.agent_backend.AgentBackendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentBackendService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthenticateUserAndPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.inter.agent_backend.AgentBackendService/AuthenticateUserAndPrompt',
            proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptRequest.SerializeToString,
            proto_dot_v1_dot_inter_dot_agent__backend_dot_backend__pb2.AuthenticateUserAndPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
