# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/v1/inter/agent_backend/backend.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/v1/inter/agent_backend/backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*proto/v1/inter/agent_backend/backend.proto\x12\x16v1.inter.agent_backend\"v\n AuthenticateUserAndPromptRequest\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x16\n\x06prompt\x18\x03 \x01(\tR\x06prompt\"9\n!AuthenticateUserAndPromptResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid2\xa8\x01\n\x13\x41gentBackendService\x12\x90\x01\n\x19\x41uthenticateUserAndPrompt\x12\x38.v1.inter.agent_backend.AuthenticateUserAndPromptRequest\x1a\x39.v1.inter.agent_backend.AuthenticateUserAndPromptResponseB2Z0vynfo.com/vynfo/gen/proto/v1/inter/agent_backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.inter.agent_backend.backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0vynfo.com/vynfo/gen/proto/v1/inter/agent_backend'
  _globals['_AUTHENTICATEUSERANDPROMPTREQUEST']._serialized_start=70
  _globals['_AUTHENTICATEUSERANDPROMPTREQUEST']._serialized_end=188
  _globals['_AUTHENTICATEUSERANDPROMPTRESPONSE']._serialized_start=190
  _globals['_AUTHENTICATEUSERANDPROMPTRESPONSE']._serialized_end=247
  _globals['_AGENTBACKENDSERVICE']._serialized_start=250
  _globals['_AGENTBACKENDSERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
