"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from proto.v1.inter.agent_backend import backend_pb2 as _backend_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AgentBackendServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AgentBackendServiceAsyncStub: ...
    AuthenticateUserAndPrompt: _grpc.UnaryUnaryMultiCallable[_backend_pb2.AuthenticateUserAndPromptRequest, _backend_pb2.AuthenticateUserAndPromptResponse]
    """TODO: expose a url signer
    TODO:
    """

@_typing.type_check_only
class AgentBackendServiceAsyncStub(AgentBackendServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    AuthenticateUserAndPrompt: _aio.UnaryUnaryMultiCallable[_backend_pb2.AuthenticateUserAndPromptRequest, _backend_pb2.AuthenticateUserAndPromptResponse]  # type: ignore[assignment]
    """TODO: expose a url signer
    TODO:
    """

class AgentBackendServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def AuthenticateUserAndPrompt(
        self,
        request: _backend_pb2.AuthenticateUserAndPromptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_backend_pb2.AuthenticateUserAndPromptResponse, _abc.Awaitable[_backend_pb2.AuthenticateUserAndPromptResponse]]:
        """TODO: expose a url signer
        TODO:
        """

def add_AgentBackendServiceServicer_to_server(servicer: AgentBackendServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
