// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_conversations.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addAIConversationMessage = `-- name: AddAIConversationMessage :one
WITH new_message AS (
    INSERT INTO ai_conversation_messages (conversation_id, run_id, message_content_as_json) VALUES ($1, $2, $3) RETURNING id, conversation_id, run_id, message_content_as_json, sent_at
), bump_conversation AS (
    UPDATE ai_conversations SET last_updated_at = (SELECT sent_at FROM new_message) WHERE id = $1
)
SELECT id, conversation_id, run_id, message_content_as_json, sent_at FROM new_message
`

type AddAIConversationMessageParams struct {
	ConversationID       uuid.UUID
	RunID                uuid.UUID
	MessageContentAsJson json.RawMessage
}

type AddAIConversationMessageRow struct {
	ID                   uuid.UUID
	ConversationID       uuid.UUID
	RunID                uuid.UUID
	MessageContentAsJson json.RawMessage
	SentAt               time.Time
}

func (q *Queries) AddAIConversationMessage(ctx context.Context, arg AddAIConversationMessageParams) (AddAIConversationMessageRow, error) {
	row := q.db.QueryRowContext(ctx, addAIConversationMessage, arg.ConversationID, arg.RunID, arg.MessageContentAsJson)
	var i AddAIConversationMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.MessageContentAsJson,
		&i.SentAt,
	)
	return i, err
}

const archiveAIConversation = `-- name: ArchiveAIConversation :one
UPDATE ai_conversations
SET is_archived = TRUE
WHERE id = $1 AND conversation_owner_id = $2
RETURNING id, title, conversation_owner_id, last_updated_at, is_archived, client_id
`

type ArchiveAIConversationParams struct {
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) ArchiveAIConversation(ctx context.Context, arg ArchiveAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, archiveAIConversation, arg.ID, arg.ConversationOwnerID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}

const assertConversationUser = `-- name: AssertConversationUser :one
SELECT EXISTS (
    SELECT 1 FROM ai_conversations
    WHERE id = $1 AND conversation_owner_id = $2
)
`

type AssertConversationUserParams struct {
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) AssertConversationUser(ctx context.Context, arg AssertConversationUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, assertConversationUser, arg.ID, arg.ConversationOwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAiConversationRun = `-- name: CreateAiConversationRun :one
INSERT INTO ai_conversation_runs (conversation_id, input_tokens, output_tokens, reasoning_tokens, num_provider_requests, num_tool_calls, run_messages) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, conversation_id, input_tokens, output_tokens, reasoning_tokens, num_provider_requests, num_tool_calls, completed_at, run_messages
`

type CreateAiConversationRunParams struct {
	ConversationID      uuid.UUID
	InputTokens         int64
	OutputTokens        int64
	ReasoningTokens     int64
	NumProviderRequests int64
	NumToolCalls        int64
	RunMessages         string
}

func (q *Queries) CreateAiConversationRun(ctx context.Context, arg CreateAiConversationRunParams) (AiConversationRun, error) {
	row := q.db.QueryRowContext(ctx, createAiConversationRun,
		arg.ConversationID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.NumProviderRequests,
		arg.NumToolCalls,
		arg.RunMessages,
	)
	var i AiConversationRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.NumProviderRequests,
		&i.NumToolCalls,
		&i.CompletedAt,
		&i.RunMessages,
	)
	return i, err
}

const deleteAIConversation = `-- name: DeleteAIConversation :execrows
DELETE FROM ai_conversations
WHERE id = $1 AND conversation_owner_id = $2
`

type DeleteAIConversationParams struct {
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) DeleteAIConversation(ctx context.Context, arg DeleteAIConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAIConversation, arg.ID, arg.ConversationOwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAIConversationByClientID = `-- name: GetAIConversationByClientID :one
SELECT id, title, conversation_owner_id, last_updated_at, is_archived, client_id
FROM ai_conversations
WHERE client_id = $1 AND conversation_owner_id = $2
`

type GetAIConversationByClientIDParams struct {
	ClientID            sql.NullString
	ConversationOwnerID uuid.UUID
}

func (q *Queries) GetAIConversationByClientID(ctx context.Context, arg GetAIConversationByClientIDParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, getAIConversationByClientID, arg.ClientID, arg.ConversationOwnerID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}

const getOrCreateAIConversation = `-- name: GetOrCreateAIConversation :one
INSERT INTO ai_conversations (title, conversation_owner_id, client_id) 
VALUES ($1, $2, $3) 
ON CONFLICT (client_id) DO UPDATE SET last_updated_at = ai_conversations.last_updated_at 
RETURNING id, title, conversation_owner_id, last_updated_at, is_archived, client_id
`

type GetOrCreateAIConversationParams struct {
	Title               string
	ConversationOwnerID uuid.UUID
	ClientID            sql.NullString
}

func (q *Queries) GetOrCreateAIConversation(ctx context.Context, arg GetOrCreateAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateAIConversation, arg.Title, arg.ConversationOwnerID, arg.ClientID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}

const getUserAIConversation = `-- name: GetUserAIConversation :one
SELECT id, title, conversation_owner_id, last_updated_at, is_archived, client_id
FROM ai_conversations
WHERE id = $1 AND conversation_owner_id = $2
`

type GetUserAIConversationParams struct {
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) GetUserAIConversation(ctx context.Context, arg GetUserAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, getUserAIConversation, arg.ID, arg.ConversationOwnerID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}

const listAIConversationMessages = `-- name: ListAIConversationMessages :many
SELECT id, conversation_id, run_id, message_content_as_json, sent_at
FROM ai_conversation_messages
WHERE conversation_id = $1
ORDER BY sent_at DESC, id DESC
LIMIT $2
`

type ListAIConversationMessagesParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

func (q *Queries) ListAIConversationMessages(ctx context.Context, arg ListAIConversationMessagesParams) ([]AiConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAIConversationMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConversationMessage
	for rows.Next() {
		var i AiConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.MessageContentAsJson,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIConversationMessagesForConversation = `-- name: ListAIConversationMessagesForConversation :many
SELECT id, conversation_id, run_id, message_content_as_json, sent_at
FROM ai_conversation_messages
WHERE conversation_id = $1
ORDER BY sent_at, id
`

func (q *Queries) ListAIConversationMessagesForConversation(ctx context.Context, conversationID uuid.UUID) ([]AiConversationMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAIConversationMessagesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConversationMessage
	for rows.Next() {
		var i AiConversationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.MessageContentAsJson,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIConversationRuns = `-- name: ListAIConversationRuns :many
SELECT id, conversation_id, input_tokens, output_tokens, reasoning_tokens, num_provider_requests, num_tool_calls, completed_at, run_messages FROM ai_conversation_runs WHERE conversation_id = $1 ORDER BY completed_at DESC, id DESC LIMIT $2
`

type ListAIConversationRunsParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

func (q *Queries) ListAIConversationRuns(ctx context.Context, arg ListAIConversationRunsParams) ([]AiConversationRun, error) {
	rows, err := q.db.QueryContext(ctx, listAIConversationRuns, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConversationRun
	for rows.Next() {
		var i AiConversationRun
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.NumProviderRequests,
			&i.NumToolCalls,
			&i.CompletedAt,
			&i.RunMessages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAIConversations = `-- name: ListUserAIConversations :many
SELECT id, title, conversation_owner_id, last_updated_at, is_archived, client_id
FROM ai_conversations
WHERE conversation_owner_id = $1
ORDER BY last_updated_at DESC
`

func (q *Queries) ListUserAIConversations(ctx context.Context, conversationOwnerID uuid.UUID) ([]AiConversation, error) {
	rows, err := q.db.QueryContext(ctx, listUserAIConversations, conversationOwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConversation
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ConversationOwnerID,
			&i.LastUpdatedAt,
			&i.IsArchived,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unArchiveAIConversation = `-- name: UnArchiveAIConversation :one
UPDATE ai_conversations
SET is_archived = FALSE
WHERE id = $1 AND conversation_owner_id = $2
RETURNING id, title, conversation_owner_id, last_updated_at, is_archived, client_id
`

type UnArchiveAIConversationParams struct {
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) UnArchiveAIConversation(ctx context.Context, arg UnArchiveAIConversationParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, unArchiveAIConversation, arg.ID, arg.ConversationOwnerID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}

const updateAIConversationTitle = `-- name: UpdateAIConversationTitle :one
UPDATE ai_conversations
SET title = $1
WHERE id = $2 AND conversation_owner_id = $3
RETURNING id, title, conversation_owner_id, last_updated_at, is_archived, client_id
`

type UpdateAIConversationTitleParams struct {
	Title               string
	ID                  uuid.UUID
	ConversationOwnerID uuid.UUID
}

func (q *Queries) UpdateAIConversationTitle(ctx context.Context, arg UpdateAIConversationTitleParams) (AiConversation, error) {
	row := q.db.QueryRowContext(ctx, updateAIConversationTitle, arg.Title, arg.ID, arg.ConversationOwnerID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ConversationOwnerID,
		&i.LastUpdatedAt,
		&i.IsArchived,
		&i.ClientID,
	)
	return i, err
}
