// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (project_id, asset_type) VALUES ($1, $2) RETURNING id, project_id, asset_type, created_at
`

type CreateAssetParams struct {
	ProjectID uuid.UUID
	AssetType string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset, arg.ProjectID, arg.AssetType)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssetType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const getProjectAssets = `-- name: GetProjectAssets :many
SELECT id, project_id, asset_type, created_at FROM assets WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) GetProjectAssets(ctx context.Context, projectID uuid.UUID) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, getProjectAssets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AssetType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
