// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audios.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAudio = `-- name: CreateAudio :one
INSERT INTO audios (asset_id, duration) VALUES ($1, $2) RETURNING asset_id, duration
`

type CreateAudioParams struct {
	AssetID  uuid.UUID
	Duration float64
}

func (q *Queries) CreateAudio(ctx context.Context, arg CreateAudioParams) (Audio, error) {
	row := q.db.QueryRowContext(ctx, createAudio, arg.AssetID, arg.Duration)
	var i Audio
	err := row.Scan(&i.AssetID, &i.Duration)
	return i, err
}

const getAudioById = `-- name: GetAudioById :one
SELECT asset_id, duration FROM audios WHERE asset_id = $1
`

func (q *Queries) GetAudioById(ctx context.Context, assetID uuid.UUID) (Audio, error) {
	row := q.db.QueryRowContext(ctx, getAudioById, assetID)
	var i Audio
	err := row.Scan(&i.AssetID, &i.Duration)
	return i, err
}

const getAudios = `-- name: GetAudios :many
SELECT asset_id, duration FROM audios WHERE asset_id = ANY($1::uuid[])
`

func (q *Queries) GetAudios(ctx context.Context, assetIds []uuid.UUID) ([]Audio, error) {
	rows, err := q.db.QueryContext(ctx, getAudios, pq.Array(assetIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audio
	for rows.Next() {
		var i Audio
		if err := rows.Scan(&i.AssetID, &i.Duration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
