// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audioframes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAudioFrame = `-- name: CreateAudioFrame :one
INSERT INTO audioframes (audio_id, timestamp_in_audio, segment_idx, byte_offset_in_segment, size_in_bytes) VALUES ($1, $2, $3, $4, $5) RETURNING audio_id, timestamp_in_audio, segment_idx, byte_offset_in_segment, size_in_bytes
`

type CreateAudioFrameParams struct {
	AudioID             uuid.UUID
	TimestampInAudio    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

func (q *Queries) CreateAudioFrame(ctx context.Context, arg CreateAudioFrameParams) (Audioframe, error) {
	row := q.db.QueryRowContext(ctx, createAudioFrame,
		arg.AudioID,
		arg.TimestampInAudio,
		arg.SegmentIdx,
		arg.ByteOffsetInSegment,
		arg.SizeInBytes,
	)
	var i Audioframe
	err := row.Scan(
		&i.AudioID,
		&i.TimestampInAudio,
		&i.SegmentIdx,
		&i.ByteOffsetInSegment,
		&i.SizeInBytes,
	)
	return i, err
}

const getAudioFrameRange = `-- name: GetAudioFrameRange :many
SELECT audio_id, timestamp_in_audio, segment_idx, byte_offset_in_segment, size_in_bytes FROM audioframes WHERE audio_id = $1 AND timestamp_in_audio >= $2 ORDER BY (segment_idx, byte_offset_in_segment) ASC LIMIT $3
`

type GetAudioFrameRangeParams struct {
	AudioID          uuid.UUID
	TimestampInAudio int64
	Limit            int32
}

func (q *Queries) GetAudioFrameRange(ctx context.Context, arg GetAudioFrameRangeParams) ([]Audioframe, error) {
	rows, err := q.db.QueryContext(ctx, getAudioFrameRange, arg.AudioID, arg.TimestampInAudio, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audioframe
	for rows.Next() {
		var i Audioframe
		if err := rows.Scan(
			&i.AudioID,
			&i.TimestampInAudio,
			&i.SegmentIdx,
			&i.ByteOffsetInSegment,
			&i.SizeInBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
