// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (project_id, name) VALUES ($1, $2) RETURNING id, project_id, name, tip_commit_id
`

type CreateBranchParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, createBranch, arg.ProjectID, arg.Name)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TipCommitID,
	)
	return i, err
}

const createMainBranch = `-- name: CreateMainBranch :one
INSERT INTO branches (project_id, name) VALUES ($1, 'main') RETURNING id, project_id, name, tip_commit_id
`

func (q *Queries) CreateMainBranch(ctx context.Context, projectID uuid.UUID) (Branch, error) {
	row := q.db.QueryRowContext(ctx, createMainBranch, projectID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TipCommitID,
	)
	return i, err
}

const getBranchByName = `-- name: GetBranchByName :one
SELECT id, project_id, name, tip_commit_id FROM branches WHERE project_id = $1 AND name = $2
`

type GetBranchByNameParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) GetBranchByName(ctx context.Context, arg GetBranchByNameParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getBranchByName, arg.ProjectID, arg.Name)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TipCommitID,
	)
	return i, err
}

const getBranchCommitHistory = `-- name: GetBranchCommitHistory :many
WITH RECURSIVE history AS (
    SELECT c.id, c.project_id, c.state, c.message, c.created_at, c.user_id
    FROM branches b
    JOIN commits c ON c.id = b.tip_commit_id
    WHERE b.id = $1

    UNION

    SELECT c.id, c.project_id, c.state, c.message, c.created_at, c.user_id
    FROM commits c
    JOIN commit_parents cp ON cp.parent_id = c.id
    JOIN history h ON h.id = cp.commit_id
)
SELECT id, project_id, state, message, created_at, user_id FROM history
`

type GetBranchCommitHistoryRow struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	State     json.RawMessage
	Message   sql.NullString
	CreatedAt sql.NullTime
	UserID    uuid.UUID
}

func (q *Queries) GetBranchCommitHistory(ctx context.Context, id uuid.UUID) ([]GetBranchCommitHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getBranchCommitHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBranchCommitHistoryRow
	for rows.Next() {
		var i GetBranchCommitHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.State,
			&i.Message,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMainBranch = `-- name: GetMainBranch :one
SELECT id, project_id, name, tip_commit_id FROM branches WHERE name = 'main'
`

func (q *Queries) GetMainBranch(ctx context.Context) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getMainBranch)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TipCommitID,
	)
	return i, err
}

const listBranchesByTipCommit = `-- name: ListBranchesByTipCommit :many
SELECT id, project_id, name, tip_commit_id FROM branches WHERE project_id = $1 AND tip_commit_id = $2
`

type ListBranchesByTipCommitParams struct {
	ProjectID   uuid.UUID
	TipCommitID uuid.NullUUID
}

func (q *Queries) ListBranchesByTipCommit(ctx context.Context, arg ListBranchesByTipCommitParams) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listBranchesByTipCommit, arg.ProjectID, arg.TipCommitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TipCommitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectBranches = `-- name: ListProjectBranches :many
SELECT id, project_id, name, tip_commit_id FROM branches WHERE project_id = $1
`

func (q *Queries) ListProjectBranches(ctx context.Context, projectID uuid.UUID) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listProjectBranches, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.TipCommitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchCommitID = `-- name: SetBranchCommitID :one
UPDATE branches SET tip_commit_id = $1 WHERE id = $2 RETURNING id, project_id, name, tip_commit_id
`

type SetBranchCommitIDParams struct {
	TipCommitID uuid.NullUUID
	ID          uuid.UUID
}

func (q *Queries) SetBranchCommitID(ctx context.Context, arg SetBranchCommitIDParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, setBranchCommitID, arg.TipCommitID, arg.ID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.TipCommitID,
	)
	return i, err
}
