// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commit_parents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCommitParent = `-- name: CreateCommitParent :one
INSERT INTO commit_parents (commit_id, parent_id, position) VALUES($1, $2, 0) RETURNING commit_id, parent_id, position
`

type CreateCommitParentParams struct {
	CommitID uuid.UUID
	ParentID uuid.UUID
}

func (q *Queries) CreateCommitParent(ctx context.Context, arg CreateCommitParentParams) (CommitParent, error) {
	row := q.db.QueryRowContext(ctx, createCommitParent, arg.CommitID, arg.ParentID)
	var i CommitParent
	err := row.Scan(&i.CommitID, &i.ParentID, &i.Position)
	return i, err
}

const createMergeCommitParents = `-- name: CreateMergeCommitParents :many
INSERT INTO commit_parents (commit_id, parent_id, position) VALUES
    ($1, $2, 0),
    ($1, $3, 1)
RETURNING commit_id, parent_id, position
`

type CreateMergeCommitParentsParams struct {
	CommitID   uuid.UUID
	ParentID   uuid.UUID
	ParentID_2 uuid.UUID
}

func (q *Queries) CreateMergeCommitParents(ctx context.Context, arg CreateMergeCommitParentsParams) ([]CommitParent, error) {
	rows, err := q.db.QueryContext(ctx, createMergeCommitParents, arg.CommitID, arg.ParentID, arg.ParentID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitParent
	for rows.Next() {
		var i CommitParent
		if err := rows.Scan(&i.CommitID, &i.ParentID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
