// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commits.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createCommit = `-- name: CreateCommit :one
INSERT INTO commits (user_id, project_id, state, message) VALUES ($1, $2, $3, $4) RETURNING id, user_id, project_id, state, message, created_at
`

type CreateCommitParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
	State     json.RawMessage
	Message   sql.NullString
}

func (q *Queries) CreateCommit(ctx context.Context, arg CreateCommitParams) (Commit, error) {
	row := q.db.QueryRowContext(ctx, createCommit,
		arg.UserID,
		arg.ProjectID,
		arg.State,
		arg.Message,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.State,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getCommitByID = `-- name: GetCommitByID :one
SELECT id, user_id, project_id, state, message, created_at FROM commits WHERE id = $1
`

func (q *Queries) GetCommitByID(ctx context.Context, id uuid.UUID) (Commit, error) {
	row := q.db.QueryRowContext(ctx, getCommitByID, id)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.State,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listUserCommits = `-- name: ListUserCommits :many
SELECT id, user_id, project_id, state, message, created_at FROM commits WHERE user_id = $1
`

func (q *Queries) ListUserCommits(ctx context.Context, userID uuid.UUID) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, listUserCommits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.State,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
