// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const changeDirectoryParent = `-- name: ChangeDirectoryParent :exec
UPDATE directories SET parent_id = $1 WHERE id = $2
`

type ChangeDirectoryParentParams struct {
	ParentID uuid.NullUUID
	ID       uuid.UUID
}

func (q *Queries) ChangeDirectoryParent(ctx context.Context, arg ChangeDirectoryParentParams) error {
	_, err := q.db.ExecContext(ctx, changeDirectoryParent, arg.ParentID, arg.ID)
	return err
}

const createDirectory = `-- name: CreateDirectory :one
INSERT INTO directories (workspace_id, display_name, parent_id) VALUES ($1, $2, $3) RETURNING id, workspace_id, display_name, parent_id, created_at, updated_at
`

type CreateDirectoryParams struct {
	WorkspaceID uuid.UUID
	DisplayName string
	ParentID    uuid.NullUUID
}

func (q *Queries) CreateDirectory(ctx context.Context, arg CreateDirectoryParams) (Directory, error) {
	row := q.db.QueryRowContext(ctx, createDirectory, arg.WorkspaceID, arg.DisplayName, arg.ParentID)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirectory = `-- name: DeleteDirectory :exec
DELETE FROM directories WHERE id = $1
`

func (q *Queries) DeleteDirectory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDirectory, id)
	return err
}

const getDirectoryById = `-- name: GetDirectoryById :one
SELECT id, workspace_id, display_name, parent_id, created_at, updated_at FROM directories WHERE id = $1
`

func (q *Queries) GetDirectoryById(ctx context.Context, id uuid.UUID) (Directory, error) {
	row := q.db.QueryRowContext(ctx, getDirectoryById, id)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DisplayName,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectoryChildren = `-- name: GetDirectoryChildren :many
SELECT id, workspace_id, display_name, parent_id, created_at, updated_at FROM directories WHERE parent_id = $1 ORDER BY created_at
`

func (q *Queries) GetDirectoryChildren(ctx context.Context, parentID uuid.NullUUID) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, getDirectoryChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directory
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootDirectories = `-- name: GetRootDirectories :many
SELECT id, workspace_id, display_name, parent_id, created_at, updated_at FROM directories WHERE parent_id IS NULL AND workspace_id = $1 ORDER BY created_at
`

func (q *Queries) GetRootDirectories(ctx context.Context, workspaceID uuid.UUID) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, getRootDirectories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directory
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirectoryName = `-- name: UpdateDirectoryName :exec
UPDATE directories SET display_name = $1 WHERE id = $2
`

type UpdateDirectoryNameParams struct {
	DisplayName string
	ID          uuid.UUID
}

func (q *Queries) UpdateDirectoryName(ctx context.Context, arg UpdateDirectoryNameParams) error {
	_, err := q.db.ExecContext(ctx, updateDirectoryName, arg.DisplayName, arg.ID)
	return err
}
