// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keyframes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createKeyFrame = `-- name: CreateKeyFrame :one
INSERT INTO keyframes (video_id, timestamp_in_video, segment_idx, byte_offset_in_segment, size_in_bytes) VALUES ($1, $2, $3, $4, $5) RETURNING video_id, timestamp_in_video, segment_idx, byte_offset_in_segment, size_in_bytes
`

type CreateKeyFrameParams struct {
	VideoID             uuid.UUID
	TimestampInVideo    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

func (q *Queries) CreateKeyFrame(ctx context.Context, arg CreateKeyFrameParams) (Keyframe, error) {
	row := q.db.QueryRowContext(ctx, createKeyFrame,
		arg.VideoID,
		arg.TimestampInVideo,
		arg.SegmentIdx,
		arg.ByteOffsetInSegment,
		arg.SizeInBytes,
	)
	var i Keyframe
	err := row.Scan(
		&i.VideoID,
		&i.TimestampInVideo,
		&i.SegmentIdx,
		&i.ByteOffsetInSegment,
		&i.SizeInBytes,
	)
	return i, err
}

const getKeyFrameRange = `-- name: GetKeyFrameRange :many
SELECT video_id, timestamp_in_video, segment_idx, byte_offset_in_segment, size_in_bytes FROM keyframes WHERE video_id = $1 AND timestamp_in_video >= $2 ORDER BY (segment_idx, byte_offset_in_segment) ASC LIMIT $3
`

type GetKeyFrameRangeParams struct {
	VideoID          uuid.UUID
	TimestampInVideo int64
	Limit            int32
}

func (q *Queries) GetKeyFrameRange(ctx context.Context, arg GetKeyFrameRangeParams) ([]Keyframe, error) {
	rows, err := q.db.QueryContext(ctx, getKeyFrameRange, arg.VideoID, arg.TimestampInVideo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyframe
	for rows.Next() {
		var i Keyframe
		if err := rows.Scan(
			&i.VideoID,
			&i.TimestampInVideo,
			&i.SegmentIdx,
			&i.ByteOffsetInSegment,
			&i.SizeInBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
