// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Asset struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	AssetType string
	CreatedAt sql.NullTime
}

type AssetType struct {
	Name string
}

type Branch struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	TipCommitID uuid.NullUUID
}

type Commit struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	State     json.RawMessage
	Message   sql.NullString
	CreatedAt sql.NullTime
}

type CommitParent struct {
	CommitID uuid.UUID
	ParentID uuid.UUID
	Position int32
}

type Project struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
	CreatedAt          sql.NullTime
	MainBranchID       uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
}

type Video struct {
	AssetID     uuid.UUID
	DisplayName string
	Duration    float64
}
