// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	AssetType string
	CreatedAt sql.NullTime
}

type AssetType struct {
	Name string
}

type Audio struct {
	AssetID     uuid.UUID
	DisplayName string
	Duration    float64
}

type Audioframe struct {
	AudioID             uuid.UUID
	TimestampInAudio    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

type Branch struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	TipCommitID uuid.NullUUID
}

type Commit struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	State     json.RawMessage
	Message   sql.NullString
	CreatedAt sql.NullTime
	UserID    uuid.UUID
}

type CommitParent struct {
	CommitID uuid.UUID
	ParentID uuid.UUID
	Position int32
}

type Image struct {
	AssetID     uuid.UUID
	DisplayName string
	ObjectPath  string
	ContentType string
}

type Keyframe struct {
	VideoID             uuid.UUID
	TimestampInVideo    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

type Message struct {
	ID         uuid.UUID
	SpaceID    uuid.UUID
	AuthorID   uuid.UUID
	ParentID   uuid.NullUUID
	Body       string
	CreatedAt  time.Time
	ReplyCount int32
}

type Project struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
	CreatedAt          sql.NullTime
	MainBranchID       uuid.NullUUID
}

type ProjectMember struct {
	ProjectID uuid.UUID
	MemberID  uuid.UUID
}

type Space struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	AdminID   uuid.UUID
	CreatedAt sql.NullTime
	Name      string
}

type SpaceMember struct {
	SpaceID  uuid.UUID
	MemberID uuid.UUID
}

type Text struct {
	AssetID     uuid.UUID
	DisplayName string
	Content     string
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
}

type Video struct {
	AssetID     uuid.UUID
	DisplayName string
	Duration    float64
}
