// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_assets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPendingAsset = `-- name: AddPendingAsset :one
INSERT INTO pending_assets (asset_id, user_id) VALUES ($1, $2) RETURNING asset_id, user_id
`

type AddPendingAssetParams struct {
	AssetID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AddPendingAsset(ctx context.Context, arg AddPendingAssetParams) (PendingAsset, error) {
	row := q.db.QueryRowContext(ctx, addPendingAsset, arg.AssetID, arg.UserID)
	var i PendingAsset
	err := row.Scan(&i.AssetID, &i.UserID)
	return i, err
}

const deletePendingAsset = `-- name: DeletePendingAsset :exec
DELETE FROM pending_assets WHERE asset_id = $1 AND user_id = $2
`

type DeletePendingAssetParams struct {
	AssetID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeletePendingAsset(ctx context.Context, arg DeletePendingAssetParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingAsset, arg.AssetID, arg.UserID)
	return err
}

const getPendingAsset = `-- name: GetPendingAsset :one
SELECT asset_id, user_id FROM pending_assets WHERE asset_id = $1 AND user_id = $2
`

type GetPendingAssetParams struct {
	AssetID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetPendingAsset(ctx context.Context, arg GetPendingAssetParams) (PendingAsset, error) {
	row := q.db.QueryRowContext(ctx, getPendingAsset, arg.AssetID, arg.UserID)
	var i PendingAsset
	err := row.Scan(&i.AssetID, &i.UserID)
	return i, err
}
