// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, project_name, project_description) VALUES ($1, $2, $3) RETURNING id, user_id, project_name, project_description, created_at, main_branch_id
`

type CreateProjectParams struct {
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.UserID, arg.ProjectName, arg.ProjectDescription)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const getUserProjects = `-- name: GetUserProjects :many
SELECT id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) GetUserProjects(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.CreatedAt,
			&i.MainBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
