// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, member_id) VALUES ($1, $2)
ON CONFLICT (project_id, member_id) DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	MemberID  uuid.UUID
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.MemberID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, user_id, project_name, project_description) VALUES ($1, $2, $3, $4) RETURNING id, workspace_id, user_id, project_name, project_description, created_at, main_branch_id
`

type CreateProjectParams struct {
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.WorkspaceID,
		arg.UserID,
		arg.ProjectName,
		arg.ProjectDescription,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const getWorkspaceProjects = `-- name: GetWorkspaceProjects :many
SELECT id, workspace_id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) GetWorkspaceProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.CreatedAt,
			&i.MainBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceProjectsWithCreators = `-- name: GetWorkspaceProjectsWithCreators :many
SELECT
    projects.id, projects.workspace_id, projects.user_id, projects.project_name, projects.project_description, projects.created_at, projects.main_branch_id,
    users.email creator_email,
    users.display_name creator_display_name,
    users.display_photo_object_path creator_display_photo_object_path
FROM projects
JOIN users ON users.id = projects.user_id
WHERE projects.workspace_id = $1
ORDER BY projects.created_at
`

type GetWorkspaceProjectsWithCreatorsRow struct {
	ID                            uuid.UUID
	WorkspaceID                   uuid.UUID
	UserID                        uuid.UUID
	ProjectName                   string
	ProjectDescription            string
	CreatedAt                     sql.NullTime
	MainBranchID                  uuid.NullUUID
	CreatorEmail                  string
	CreatorDisplayName            sql.NullString
	CreatorDisplayPhotoObjectPath sql.NullString
}

func (q *Queries) GetWorkspaceProjectsWithCreators(ctx context.Context, workspaceID uuid.UUID) ([]GetWorkspaceProjectsWithCreatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWorkspaceProjectsWithCreators, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceProjectsWithCreatorsRow
	for rows.Next() {
		var i GetWorkspaceProjectsWithCreatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.CreatedAt,
			&i.MainBranchID,
			&i.CreatorEmail,
			&i.CreatorDisplayName,
			&i.CreatorDisplayPhotoObjectPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetFromProject = `-- name: RemoveAssetFromProject :exec
DELETE FROM project_assets WHERE project_id = $1 AND asset_id = $2
`

type RemoveAssetFromProjectParams struct {
	ProjectID uuid.UUID
	AssetID   uuid.UUID
}

func (q *Queries) RemoveAssetFromProject(ctx context.Context, arg RemoveAssetFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, removeAssetFromProject, arg.ProjectID, arg.AssetID)
	return err
}

const setMainBranch = `-- name: SetMainBranch :one
UPDATE projects SET main_branch_id = $1 WHERE id = $2 RETURNING id, workspace_id, user_id, project_name, project_description, created_at, main_branch_id
`

type SetMainBranchParams struct {
	MainBranchID uuid.NullUUID
	ID           uuid.UUID
}

func (q *Queries) SetMainBranch(ctx context.Context, arg SetMainBranchParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, setMainBranch, arg.MainBranchID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}
