// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, member_id) VALUES ($1, $2)
ON CONFLICT (project_id, member_id) DO NOTHING
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	MemberID  uuid.UUID
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.MemberID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, project_name, project_description) VALUES ($1, $2, $3) RETURNING id, user_id, project_name, project_description, created_at, main_branch_id
`

type CreateProjectParams struct {
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.UserID, arg.ProjectName, arg.ProjectDescription)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}

const getUserCreatedProjects = `-- name: GetUserCreatedProjects :many
SELECT id, user_id, project_name, project_description, created_at, main_branch_id FROM projects WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) GetUserCreatedProjects(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getUserCreatedProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.CreatedAt,
			&i.MainBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMemberProjects = `-- name: GetUserMemberProjects :many
SELECT projects.id, projects.user_id, projects.project_name, projects.project_description, projects.created_at, projects.main_branch_id FROM projects
JOIN project_members ON project_members.project_id = projects.id
WHERE project_members.member_id = $1 AND projects.user_id <> $1
ORDER BY projects.created_at
`

func (q *Queries) GetUserMemberProjects(ctx context.Context, memberID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getUserMemberProjects, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectDescription,
			&i.CreatedAt,
			&i.MainBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMainBranch = `-- name: SetMainBranch :one
UPDATE projects SET main_branch_id = $1 WHERE id = $2 RETURNING id, user_id, project_name, project_description, created_at, main_branch_id
`

type SetMainBranchParams struct {
	MainBranchID uuid.NullUUID
	ID           uuid.UUID
}

func (q *Queries) SetMainBranch(ctx context.Context, arg SetMainBranchParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, setMainBranch, arg.MainBranchID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectDescription,
		&i.CreatedAt,
		&i.MainBranchID,
	)
	return i, err
}
