// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addBranchedMessageToSpace = `-- name: AddBranchedMessageToSpace :one
with new_message AS (
    INSERT INTO messages (space_id, author_id, body, parent_id) VALUES ($1, $2, $3, $4) RETURNING id, space_id, author_id, parent_id, body, created_at, reply_count
), bump_reply_count AS (
    UPDATE messages SET reply_count = reply_count + 1 WHERE id = $4
) SELECT id, space_id, author_id, parent_id, body, created_at, reply_count FROM new_message
`

type AddBranchedMessageToSpaceParams struct {
	SpaceID  uuid.UUID
	AuthorID uuid.UUID
	Body     string
	ParentID uuid.NullUUID
}

type AddBranchedMessageToSpaceRow struct {
	ID         uuid.UUID
	SpaceID    uuid.UUID
	AuthorID   uuid.UUID
	ParentID   uuid.NullUUID
	Body       string
	CreatedAt  time.Time
	ReplyCount int32
}

func (q *Queries) AddBranchedMessageToSpace(ctx context.Context, arg AddBranchedMessageToSpaceParams) (AddBranchedMessageToSpaceRow, error) {
	row := q.db.QueryRowContext(ctx, addBranchedMessageToSpace,
		arg.SpaceID,
		arg.AuthorID,
		arg.Body,
		arg.ParentID,
	)
	var i AddBranchedMessageToSpaceRow
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.ReplyCount,
	)
	return i, err
}

const addMessageToSpace = `-- name: AddMessageToSpace :one
INSERT INTO messages (space_id, author_id, body) VALUES ($1, $2, $3) RETURNING id, space_id, author_id, parent_id, body, created_at, reply_count
`

type AddMessageToSpaceParams struct {
	SpaceID  uuid.UUID
	AuthorID uuid.UUID
	Body     string
}

func (q *Queries) AddMessageToSpace(ctx context.Context, arg AddMessageToSpaceParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, addMessageToSpace, arg.SpaceID, arg.AuthorID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.CreatedAt,
		&i.ReplyCount,
	)
	return i, err
}

const addSpaceMember = `-- name: AddSpaceMember :exec
INSERT INTO space_members (space_id, member_id) VALUES ($1, $2)
ON CONFLICT (space_id, member_id) DO NOTHING
`

type AddSpaceMemberParams struct {
	SpaceID  uuid.UUID
	MemberID uuid.UUID
}

func (q *Queries) AddSpaceMember(ctx context.Context, arg AddSpaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, addSpaceMember, arg.SpaceID, arg.MemberID)
	return err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (project_id, admin_id, name) VALUES ($1, $2, $3) RETURNING id, project_id, admin_id, created_at, name
`

type CreateSpaceParams struct {
	ProjectID uuid.UUID
	AdminID   uuid.UUID
	Name      string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace, arg.ProjectID, arg.AdminID, arg.Name)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AdminID,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getProjectSpaces = `-- name: GetProjectSpaces :many
SELECT id, project_id, admin_id, created_at, name FROM spaces WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProjectSpaces(ctx context.Context, projectID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, getProjectSpaces, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AdminID,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectSpacesWithMembers = `-- name: GetProjectSpacesWithMembers :many
SELECT
    s.id AS space_id,
    s.project_id,
    s.admin_id,
    s.name,
    s.created_at,
    u.id AS member_id,
    u.email AS member_email
FROM spaces s
LEFT JOIN space_members sm ON sm.space_id = s.id
LEFT JOIN users u ON u.id = sm.member_id
WHERE s.project_id = $1
ORDER BY s.created_at DESC, u.email
`

type GetProjectSpacesWithMembersRow struct {
	SpaceID     uuid.UUID
	ProjectID   uuid.UUID
	AdminID     uuid.UUID
	Name        string
	CreatedAt   sql.NullTime
	MemberID    uuid.NullUUID
	MemberEmail sql.NullString
}

func (q *Queries) GetProjectSpacesWithMembers(ctx context.Context, projectID uuid.UUID) ([]GetProjectSpacesWithMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getProjectSpacesWithMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectSpacesWithMembersRow
	for rows.Next() {
		var i GetProjectSpacesWithMembersRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.ProjectID,
			&i.AdminID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberID,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpace = `-- name: GetSpace :one
SELECT id, project_id, admin_id, created_at, name FROM spaces WHERE id = $1
`

func (q *Queries) GetSpace(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpace, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AdminID,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getSpaceMembers = `-- name: GetSpaceMembers :many
SELECT space_id, member_id FROM space_members WHERE space_id = $1
`

func (q *Queries) GetSpaceMembers(ctx context.Context, spaceID uuid.UUID) ([]SpaceMember, error) {
	rows, err := q.db.QueryContext(ctx, getSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpaceMember
	for rows.Next() {
		var i SpaceMember
		if err := rows.Scan(&i.SpaceID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSpaces = `-- name: GetUserSpaces :many
SELECT id, project_id, admin_id, created_at, name FROM spaces WHERE id IN (
    SELECT space_id FROM space_members WHERE member_id = $1
)
`

func (q *Queries) GetUserSpaces(ctx context.Context, memberID uuid.UUID) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, getUserSpaces, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AdminID,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSpacesWithMembers = `-- name: GetUserSpacesWithMembers :many
SELECT
    s.id AS space_id,
    s.project_id,
    s.admin_id,
    s.name,
    s.created_at,
    u.id AS member_id,
    u.email AS member_email
FROM spaces s
JOIN space_members requested_member ON requested_member.space_id = s.id
LEFT JOIN space_members sm ON sm.space_id = s.id
LEFT JOIN users u ON u.id = sm.member_id
WHERE requested_member.member_id = $1
ORDER BY s.created_at DESC, u.email
`

type GetUserSpacesWithMembersRow struct {
	SpaceID     uuid.UUID
	ProjectID   uuid.UUID
	AdminID     uuid.UUID
	Name        string
	CreatedAt   sql.NullTime
	MemberID    uuid.NullUUID
	MemberEmail sql.NullString
}

func (q *Queries) GetUserSpacesWithMembers(ctx context.Context, memberID uuid.UUID) ([]GetUserSpacesWithMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSpacesWithMembers, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSpacesWithMembersRow
	for rows.Next() {
		var i GetUserSpacesWithMembersRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.ProjectID,
			&i.AdminID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberID,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMessages = `-- name: ListSpaceMessages :many
SELECT
    m.id,
    m.space_id,
    m.author_id,
    m.parent_id,
    m.body,
    m.created_at,
    m.reply_count,
    u.email author_email
FROM messages m
JOIN users u ON u.id = m.author_id
WHERE m.space_id = $1
  AND m.parent_id IS NOT DISTINCT FROM $2
ORDER BY m.created_at
`

type ListSpaceMessagesParams struct {
	SpaceID  uuid.UUID
	ParentID uuid.NullUUID
}

type ListSpaceMessagesRow struct {
	ID          uuid.UUID
	SpaceID     uuid.UUID
	AuthorID    uuid.UUID
	ParentID    uuid.NullUUID
	Body        string
	CreatedAt   time.Time
	ReplyCount  int32
	AuthorEmail string
}

func (q *Queries) ListSpaceMessages(ctx context.Context, arg ListSpaceMessagesParams) ([]ListSpaceMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpaceMessages, arg.SpaceID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpaceMessagesRow
	for rows.Next() {
		var i ListSpaceMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.CreatedAt,
			&i.ReplyCount,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const triggerSpaceNotification = `-- name: TriggerSpaceNotification :exec
SELECT pg_notify('space_change', $1::TEXT)
`

func (q *Queries) TriggerSpaceNotification(ctx context.Context, spaceID string) error {
	_, err := q.db.ExecContext(ctx, triggerSpaceNotification, spaceID)
	return err
}
