// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: texts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createText = `-- name: CreateText :one
INSERT INTO texts (asset_id, display_name, content) VALUES ($1, $2, $3) RETURNING asset_id, display_name, content
`

type CreateTextParams struct {
	AssetID     uuid.UUID
	DisplayName string
	Content     string
}

func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, createText, arg.AssetID, arg.DisplayName, arg.Content)
	var i Text
	err := row.Scan(&i.AssetID, &i.DisplayName, &i.Content)
	return i, err
}

const getTextById = `-- name: GetTextById :one
SELECT asset_id, display_name, content FROM texts WHERE asset_id = $1
`

func (q *Queries) GetTextById(ctx context.Context, assetID uuid.UUID) (Text, error) {
	row := q.db.QueryRowContext(ctx, getTextById, assetID)
	var i Text
	err := row.Scan(&i.AssetID, &i.DisplayName, &i.Content)
	return i, err
}
