// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (asset_id, display_name, duration) VALUES ($1, $2, $3) RETURNING asset_id, display_name, duration
`

type CreateVideoParams struct {
	AssetID     uuid.UUID
	DisplayName string
	Duration    float64
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo, arg.AssetID, arg.DisplayName, arg.Duration)
	var i Video
	err := row.Scan(&i.AssetID, &i.DisplayName, &i.Duration)
	return i, err
}

const getVideoById = `-- name: GetVideoById :one
SELECT asset_id, display_name, duration FROM videos WHERE asset_id = $1
`

func (q *Queries) GetVideoById(ctx context.Context, assetID uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoById, assetID)
	var i Video
	err := row.Scan(&i.AssetID, &i.DisplayName, &i.Duration)
	return i, err
}

const getVideos = `-- name: GetVideos :many
SELECT asset_id, display_name, duration FROM videos WHERE asset_id = ANY($1::uuid[])
`

func (q *Queries) GetVideos(ctx context.Context, assetIds []uuid.UUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideos, pq.Array(assetIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(&i.AssetID, &i.DisplayName, &i.Duration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
