# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/v1/internal/agent_runtime/chat.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto/v1/internal/agent_runtime/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*proto/v1/internal/agent_runtime/chat.proto\x12\x19v1.internal.agent_runtime\"T\n\x11StreamChatRequest\x12\x16\n\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\'\n\x0f\x63onversation_id\x18\x02 \x01(\tR\x0e\x63onversationId\"\xc9\x02\n\x12StreamChatResponse\x12\x1d\n\nmessage_id\x18\x01 \x01(\tR\tmessageId\x12:\n\x04text\x18\x02 \x01(\x0b\x32$.v1.internal.agent_runtime.TextDeltaH\x00R\x04text\x12I\n\treasoning\x18\x03 \x01(\x0b\x32).v1.internal.agent_runtime.ReasoningDeltaH\x00R\treasoning\x12\x42\n\ttool_call\x18\x04 \x01(\x0b\x32#.v1.internal.agent_runtime.ToolCallH\x00R\x08toolCall\x12\x41\n\x08\x66inished\x18\x05 \x01(\x0b\x32#.v1.internal.agent_runtime.FinishedH\x00R\x08\x66inishedB\x06\n\x04\x62ody\"%\n\tTextDelta\x12\x18\n\x07\x63ontent\x18\x01 \x01(\tR\x07\x63ontent\"*\n\x0eReasoningDelta\x12\x18\n\x07\x63ontent\x18\x01 \x01(\tR\x07\x63ontent\"\n\n\x08\x46inished\"\xee\x01\n\x08ToolCall\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32).v1.internal.agent_runtime.ToolCallStatusR\x06status\x12I\n\nweb_search\x18\x02 \x01(\x0b\x32(.v1.internal.agent_runtime.ToolWebSearchH\x00R\twebSearch\x12L\n\npage_fetch\x18\x03 \x01(\x0b\x32+.v1.internal.agent_runtime.ToolFetchWebPageH\x00R\tpageFetchB\x06\n\x04\x63\x61ll\"%\n\rToolWebSearch\x12\x14\n\x05query\x18\x01 \x01(\tR\x05query\"&\n\x10ToolFetchWebPage\x12\x12\n\x04urls\x18\x02 \x03(\tR\x04urls*\xac\x01\n\x0eToolCallStatus\x12 \n\x1cTOOL_CALL_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n\x1aTOOL_CALL_STATUS_REQUESTED\x10\x01\x12\x1d\n\x19TOOL_CALL_STATUS_COMPLETE\x10\x02\x12\x1b\n\x17TOOL_CALL_STATUS_DENIED\x10\x03\x12\x1c\n\x18TOOL_CALL_STATUS_ERRORED\x10\x04\x32z\n\x0b\x43hatService\x12k\n\nStreamChat\x12,.v1.internal.agent_runtime.StreamChatRequest\x1a-.v1.internal.agent_runtime.StreamChatResponse0\x01\x42\x35Z3vynfo.com/vynfo/gen/proto/v1/internal/agent_runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.v1.internal.agent_runtime.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3vynfo.com/vynfo/gen/proto/v1/internal/agent_runtime'
  _globals['_TOOLCALLSTATUS']._serialized_start=907
  _globals['_TOOLCALLSTATUS']._serialized_end=1079
  _globals['_STREAMCHATREQUEST']._serialized_start=73
  _globals['_STREAMCHATREQUEST']._serialized_end=157
  _globals['_STREAMCHATRESPONSE']._serialized_start=160
  _globals['_STREAMCHATRESPONSE']._serialized_end=489
  _globals['_TEXTDELTA']._serialized_start=491
  _globals['_TEXTDELTA']._serialized_end=528
  _globals['_REASONINGDELTA']._serialized_start=530
  _globals['_REASONINGDELTA']._serialized_end=572
  _globals['_FINISHED']._serialized_start=574
  _globals['_FINISHED']._serialized_end=584
  _globals['_TOOLCALL']._serialized_start=587
  _globals['_TOOLCALL']._serialized_end=825
  _globals['_TOOLWEBSEARCH']._serialized_start=827
  _globals['_TOOLWEBSEARCH']._serialized_end=864
  _globals['_TOOLFETCHWEBPAGE']._serialized_start=866
  _globals['_TOOLFETCHWEBPAGE']._serialized_end=904
  _globals['_CHATSERVICE']._serialized_start=1081
  _globals['_CHATSERVICE']._serialized_end=1203
# @@protoc_insertion_point(module_scope)
