# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.v1.internal.agent_runtime import chat_pb2 as proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/v1.internal.agent_runtime.ChatService/StreamChat',
                request_serializer=proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatRequest.SerializeToString,
                response_deserializer=proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatRequest.FromString,
                    response_serializer=proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.internal.agent_runtime.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.internal.agent_runtime.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1.internal.agent_runtime.ChatService/StreamChat',
            proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatRequest.SerializeToString,
            proto_dot_v1_dot_internal_dot_agent__runtime_dot_chat__pb2.StreamChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
