// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AiConversation struct {
	ID                  uuid.UUID
	Title               string
	ConversationOwnerID uuid.UUID
	LastUpdatedAt       time.Time
	IsArchived          bool
	ClientID            sql.NullString
	ProjectID           uuid.NullUUID
}

type AiConversationMessage struct {
	ID                   uuid.UUID
	ConversationID       uuid.UUID
	RunID                uuid.UUID
	MessageContentAsJson json.RawMessage
	SentAt               time.Time
	ClientID             string
	ParentID             uuid.NullUUID
	Position             int32
	Ordinal              sql.NullInt64
}

type AiConversationRun struct {
	ID                  uuid.UUID
	ConversationID      uuid.UUID
	InputTokens         int64
	OutputTokens        int64
	ReasoningTokens     int64
	NumProviderRequests int64
	NumToolCalls        int64
	CompletedAt         time.Time
	RunMessages         string
}

type Asset struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	AssetType   string
	DisplayName string
	CreatedAt   sql.NullTime
	DirectoryID uuid.NullUUID
}

type AssetType struct {
	Name string
}

type Audio struct {
	AssetID  uuid.UUID
	Duration float64
}

type Audioframe struct {
	AudioID             uuid.UUID
	TimestampInAudio    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

type Branch struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	TipCommitID uuid.NullUUID
}

type Commit struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProjectID uuid.UUID
	State     json.RawMessage
	Message   sql.NullString
	CreatedAt sql.NullTime
}

type CommitParent struct {
	CommitID uuid.UUID
	ParentID uuid.UUID
	Position int32
}

type Directory struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DisplayName string
	ParentID    uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Image struct {
	AssetID     uuid.UUID
	ObjectPath  string
	ContentType string
}

type Keyframe struct {
	VideoID             uuid.UUID
	TimestampInVideo    int64
	SegmentIdx          int64
	ByteOffsetInSegment int64
	SizeInBytes         int64
}

type Message struct {
	ID         uuid.UUID
	SpaceID    uuid.UUID
	AuthorID   uuid.UUID
	ParentID   uuid.NullUUID
	Body       string
	CreatedAt  time.Time
	ReplyCount int32
}

type PendingAsset struct {
	AssetID uuid.UUID
	UserID  uuid.UUID
}

type Project struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	ProjectName        string
	ProjectDescription string
	CreatedAt          sql.NullTime
	MainBranchID       uuid.NullUUID
}

type ProjectAsset struct {
	ProjectID uuid.UUID
	AssetID   uuid.UUID
}

type ProjectMember struct {
	ProjectID uuid.UUID
	MemberID  uuid.UUID
}

type Space struct {
	ID          uuid.UUID
	AdminID     uuid.UUID
	Name        string
	WorkspaceID uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type SpaceMember struct {
	SpaceID  uuid.UUID
	MemberID uuid.UUID
}

type User struct {
	ID                     uuid.UUID
	FirebaseUid            string
	Email                  string
	DisplayName            sql.NullString
	DisplayPhotoObjectPath sql.NullString
	OnboardedAt            sql.NullTime
	CreatedAt              sql.NullTime
}

type Video struct {
	AssetID  uuid.UUID
	Duration float64
	HasAudio bool
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	MemberID    uuid.UUID
}
